### ISSUE TITLE
Title slide: Introduction to GitHub

### ISSUE THREAD

**Issue by kacres** [chrisbean/Mastering_GitHub#5]
![image](https://user-images.githubusercontent.com/28354997/95037187-2033e680-0698-11eb-8048-6479c952ac79.png)

- [ ] Create a hook to engage people. Make each lesson start with a fun intro that is playful

Thoughts:

- I think that we should make the intro more catchy. I want to hook people right from the start and bullet points don’t do that.
- Perhaps we use a sentence here that is fun and catchy like we spoke about in our meeting today.
- Even something simple like taking the bullet points and making them into a sentence might be better. 
Or make it into a narrative like: You are likely here because you keep going to these meetings and everyone is  talking about Git and GitHub and you are saying to yourself “What is the big deal?”... (you can likely do better :)

**Comment by chrisbean** [comment]
current intro: "You're probably here because you've heard a lot of buzz about GitHub. Maybe your manager told you to take this course, or a stakeholder wants you to "create an issue." Maybe you're not completely sold on why GitHub is important to your job. You're in the right place to find out what exactly is up with Git and GitHub at Shopify."
